package com.cricketanalyser;

public enum SortField {
    AVERAGE,STRIKE_RATE,MAXIMUM_BOUNDARIES,MAX_RUNS,AVERAGEWITHSTRIKERATE, RUNS_WITH_AVERAGE, MAXIMUM_BOUNDARIES_WITH_STRIKE, ECONOMY, STRIKE_RATE_WITH_WICKETS;
}
